version: "3.0"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - /var/storage/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - weather_station

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/storage/grafana:/var/lib/grafana
    restart: always
    depends_on:
      - database
    networks:
      - weather_station

  api:
    image: weatherstation_api:latest
    container_name: api
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 8080
      DATABASE_HOST: database
      DATABASE_NAME: WeatherStation
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      API_ENDPOINT: /weatherstation/windrain
      PARAM_WIND_DIRECTION: winddir
      PARAM_WIND_SPEED: windspeed
      PARAM_RAINFALL: rainfall
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    networks:
      - weather_station

  manager:
    image: database_manager:latest
    container_name: manager
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: WeatherStation
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DELETION_FREQUENCY_HOURS: 1
      TIME_WINDOW_DAYS: 0
      TIME_WINDOW_HOURS: 0
      TIME_WINDOW_MINUTES: 0
      TIME_WINDOW_SECONDS: 20
    restart: always
    depends_on:
      - database
    networks:
      - weather_station

networks:
  weather_station:
    driver: bridge
