version: "3.0"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - weather_station

networks:
  weather_station:
    external: true
