version: "3.0"

services:
  api:
    image: weatherstation_api:latest
    container_name: api
    environment:
      WEATHERSTATION_PASSPHRASE: makerspace
      DATABASE_HOST: database
      DATABASE_NAME: WeatherStation
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    ports:
      - "8080:80"
    restart: always

networks:
  default:
    external:
      name: backend_weather_station


