version: "3.5"

services:
  api:
    image: weatherstation_api:latest
    container_name: api
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 8080
      DATABASE_HOST: database
      DATABASE_NAME: WeatherStation
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      API_ENDPOINT: /weatherstation/windrain
      PARAM_WIND_DIRECTION: winddir
      PARAM_WIND_SPEED: windspeed
      PARAM_RAINFALL: rainfall
    ports:
      - "8080:8080"
    restart: always
    networks:
      - weatherstation

networks:
  weatherstation:
    external: true


