version: "3.0"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - /var/storage/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - weather_station

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
    networks:
      - weather_station

networks:
  weather_station:
    driver: bridge
